#!/usr/bin/env python3
"""Generates the Penny launcher icon (a one-cent coin, flat Material style) as adaptive-icon vector drawables.

Usage: python3 tools/launcher_icon.py [preview.svg]   (run from android/)
Writes app/src/main/res/drawable/ic_launcher_{background,foreground,monochrome}.xml and optionally an SVG
preview showing the icon under a circle mask, a squircle mask and as a themed icon.
"""
import math, os, sys

C = 54.0  # centre of the 108x108 adaptive-icon canvas

# Colours from the app theme (ui/Theme.kt, dark scheme): primaryContainer / onPrimaryContainer.
BACKGROUND_COLOR = "#00513A"
COIN_COLOR = "#A7F2CD"

def f(v):
    s = f"{v:.2f}".rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s

def circle(r, cx=C, cy=C):
    return f"M{f(cx - r)},{f(cy)}a{f(r)},{f(r)} 0,1 1,{f(2 * r)},0a{f(r)},{f(r)} 0,1 1,{f(-2 * r)},0z"

def ring(r_out, r_in):
    # Outer clockwise, inner counter-clockwise, so the default nonZero fill leaves a hole.
    inner = f"M{f(C - r_in)},{f(C)}a{f(r_in)},{f(r_in)} 0,1 0,{f(2 * r_in)},0a{f(r_in)},{f(r_in)} 0,1 0,{f(-2 * r_in)},0z"
    return circle(r_out) + inner

def grain(x, y, ang, length, width):
    """A wheat grain: a pointed oval (vesica) from (x, y) pointing along ang (radians)."""
    tx, ty = x + length * math.cos(ang), y + length * math.sin(ang)
    half, s = length / 2, width / 2
    r = (half * half + s * s) / (2 * s)
    return f"M{f(x)},{f(y)}A{f(r)},{f(r)} 0,0 1,{f(tx)},{f(ty)}A{f(r)},{f(r)} 0,0 1,{f(x)},{f(y)}z"

def wheat(mirror, R=15.8, start=128, end=200, pairs=3, length=4.8, width=2.4, stalk=0.7):
    """One wheat ear curving up the left (or mirrored right) side of the coin."""
    a0, a1 = math.radians(start), math.radians(end)
    mx = (lambda x: 2 * C - x) if mirror else (lambda x: x)
    at = lambda r, a: (C + r * math.cos(a), C + r * math.sin(a))

    def aim(a, off):
        # Direction along the stalk (increasing angle runs upwards on the left), turned by off.
        t = a + math.pi / 2 + off
        ex, ey = math.cos(t), math.sin(t)
        return math.atan2(ey, -ex if mirror else ex)

    (x0, y0), (x1, y1) = at(R + stalk, a0), at(R + stalk, a1)
    (x2, y2), (x3, y3) = at(R - stalk, a1), at(R - stalk, a0)
    up, down = (0, 1) if mirror else (1, 0)
    paths = [f"M{f(mx(x0))},{f(y0)}A{f(R + stalk)},{f(R + stalk)} 0,0 {up},{f(mx(x1))},{f(y1)}"
             f"L{f(mx(x2))},{f(y2)}A{f(R - stalk)},{f(R - stalk)} 0,0 {down},{f(mx(x3))},{f(y3)}z"]
    step = (end - start - 10) / pairs
    for i in range(pairs):
        a = math.radians(start + 14 + i * step)
        x, y = at(R, a)
        paths.append(grain(mx(x), y, aim(a, -0.62), length, width))
        paths.append(grain(mx(x), y, aim(a, 0.62), length, width))
    x, y = at(R, a1)
    paths.append(grain(mx(x), y, aim(a1, 0), length * 1.05, width))
    return "".join(paths)

def beads(r=22.6, n=30, size=0.95):
    return "".join(circle(size, C + r * math.cos(2 * math.pi * i / n), C + r * math.sin(2 * math.pi * i / n)) for i in range(n))

# Bold sans-serif numeral "1", centred on the coin.
ONE = "M56.5,42L56.5,65.5L51,65.5L51,48.6L46.8,50.6L45.4,46.2L52.2,42z"

GLYPH = ring(29, 25.6) + beads() + wheat(False) + wheat(True) + ONE

BACKGROUND = [(f"M0,0h108v108h-108z", BACKGROUND_COLOR)]
FOREGROUND = [(GLYPH, COIN_COLOR)]
MONOCHROME = [(GLYPH, "#FFFFFF")]

def vector(layers):
    out = ['<?xml version="1.0" encoding="utf-8"?>',
           '<!-- Generated by tools/launcher_icon.py; edit that and rerun instead of this file. -->',
           '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
           '    android:width="108dp"', '    android:height="108dp"',
           '    android:viewportWidth="108"', '    android:viewportHeight="108">']
    for d, fill in layers:
        out.append(f'    <path\n        android:fillColor="{fill}"\n        android:pathData="{d}" />')
    out.append('</vector>')
    return "\n".join(out) + "\n"

def preview(path):
    """Icons as a launcher shows them: circle mask, squircle mask, and the themed (monochrome) icon."""
    def tile(x, clip, bg, fg):
        return (f'<g transform="translate({x},0)"><g clip-path="url(#{clip})" transform="translate(-18,-18)">'
                f'<rect width="108" height="108" fill="{bg}"/><path d="{GLYPH}" fill="{fg}"/></g></g>')
    s = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="-6 -6 252 84" width="1260" height="420">'
         f'<rect x="-6" y="-6" width="252" height="84" fill="#E8EEF0"/><defs>'
         '<clipPath id="circ"><circle cx="54" cy="54" r="36"/></clipPath>'
         '<clipPath id="sq"><rect x="18" y="18" width="72" height="72" rx="20"/></clipPath></defs>'
         + tile(0, "circ", BACKGROUND_COLOR, COIN_COLOR) + tile(84, "sq", BACKGROUND_COLOR, COIN_COLOR)
         + tile(168, "circ", "#DCE5DD", "#2F4A3B") + "</svg>")
    open(path, "w").write(s)

if __name__ == "__main__":
    res = os.path.join(os.path.dirname(os.path.abspath(__file__)), "../app/src/main/res/drawable")
    open(os.path.join(res, "ic_launcher_background.xml"), "w").write(vector(BACKGROUND))
    open(os.path.join(res, "ic_launcher_foreground.xml"), "w").write(vector(FOREGROUND))
    open(os.path.join(res, "ic_launcher_monochrome.xml"), "w").write(vector(MONOCHROME))
    if len(sys.argv) > 1:
        preview(sys.argv[1])
